### ISSUE TITLE
Question: how to change the bubble color?

### ISSUE THREAD

**Issue by Cammagno** [adifyr/obsidian-chat-view#1]
Hi!

Beautiful plugin! :)

I've been able to customize almost everything using css, but not the color of the bubble around messages.

I've tried things as:

.chat-view-bubble {
background-color: yellow !important;
}

but without success.

May you please address me to a way to do it?

**Comment by adifyr** [comment]
Hi! Have you done this in your `snippets.css` file? If so, did you enable and reload the `snippets.css`? I was able to do this successfully with the same exact code:

```
.chat-view-bubble {
    background-color: yellow !important;
}
```

**Comment by Cammagno** [comment]
> Hi! Have you done this in your `snippets.css` file? If so, did you enable and reload the `snippets.css`? I was able to do this successfully with the same exact code in my own `snippets.css`:

I've found a really funny thing happening:
if the css is called MAC - B.css, MAC - C.css or MAC - D.css (also with some other letters after the B, C and D), the bubble part does not work (while the other ones about header, message, subtext and so on do work normally).
With other names, even similar ones (such as MAC- A, MAC - E.css and so on) also the bubble part works normally.
No idea if it's general or due to some exotic combination of plugins I may have 
So, changing the css name from MAC - Chat.css to MAC - Talk.css solved the problem for me :D 

> Also, my plugin hasn't even been officially released yet. How did you come across it? 😅 And what are you using it for? 😃

I've seen your request for its inclusion in the Community Plugin in the Updates channel of Obsidian Discord and I immediately tested it, loved it and advertised it on the Obsidian TTRPG FB group I'm admin of :D 
I'm using it to reproduce conversation between NPCs in my games :)

**Comment by adifyr** [comment]
Hi! Glad to see your issue got resolved.
Thanks for letting me know what you're using it for! It's great to hear stories from users on the different ways their using the plugin! 😁

**Comment by Cammagno** [comment]
I would like to add a feature request:
can the chat-vew-<color> class be added also to the bubble div?
In that way, one can use css to personalize the bubble differently for different speaking names :)
