### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ollecello** [adifyr/obsidian-chat-view#15]
Not being able to install Version 1.2.1
--> "Failed to install" message.

**Comment by Adrien-3** [comment]
Same issue, and same error here. First time installing the plugin but it is failing :(

**Comment by Cammagno** [comment]
same problem with 1.2.1

**Comment by berot3** [comment]
same. I am getting `Error: Request failed, status 404`

![image](https://user-images.githubusercontent.com/52616/197160312-5763bab4-27e9-4667-9b62-691e1b382e05.png)

**Comment by adifyr** [comment]
Hi @ollecello @Cammagno @berot3. Version `1.2.1` was currently as a draft. With no `main.js` file included. I've officially published version `1.2.1` with all the requisite files.

Please let me know if the issue persists. Awaiting your feedback.

**Comment by adifyr** [comment]
Thanks for the update!

As far as your 2nd query goes, It's not really an issue related to my plugin. Why don't you make a post on the [Obsidian Forum](https://forum.obsidian.md/)? You should find people to help you with your problem there.

Closing this issue.
