### ISSUE TITLE
FR: Support markdown syntax in chats

### ISSUE THREAD

**Issue by JeloKuneho** [adifyr/obsidian-chat-view#16]
Currently, text can only appear in plaintext. For example, when you surround text with `** **` or insert links (internal or external) like so

![image](https://user-images.githubusercontent.com/99579095/200467320-3aede81d-ee9e-4c1c-bd0b-5cd48cd93741.png)

the text is rendered in plaintext. Cannot click on links to open them.

![image](https://user-images.githubusercontent.com/99579095/200467553-d59fd443-b0b0-42bf-8f14-7db6002f4bd0.png)

Adding markdown support would enhance the capabilities of the plugin.

By the way, thank you for this plugin 🍪. I like to use it to create clean views of conversations.

**Comment by adifyr** [comment]
I may be able to support general markdown syntax. Internal links, however, are a Obsidian specific feature. I won't be able to put that in there.

**Comment by adifyr** [comment]
Hi @JeloKuneho. With the latest release of the Chat View Plugin: Version 1.3.0, I have added Markdown and HTML Rendering Support to the Chat View Message. Please refer to the [README](https://github.com/adifyr/obsidian-chat-view/blob/master/README.md#markdown--html-support-in-chat-view-message) for more information.

Closing this issue.

**Comment by JeloKuneho** [comment]
Yep, its working good. Thank you!
