### ISSUE TITLE
FR: Multiline / Linebreak Support

### ISSUE THREAD

**Issue by msnr** [adifyr/obsidian-chat-view#17]
I solely use this plugin to archive memorable chats from messengers and if its a longer message with linebreaks, links, lists, etc. it's hard to read in Chat View.

Here an example:

Messenger:
![grafik](https://user-images.githubusercontent.com/12184406/202160214-836fd7dd-a74d-47bd-b477-ccb7d5075873.png)

Chat View:
![grafik](https://user-images.githubusercontent.com/12184406/202160365-b9c99d80-d69c-47b4-bb19-091fb84cf414.png)

I could imagine the following sulotions:
1. a special seperator char for multiline, so it doesn't have to be a oneliner anymore (wrap it in `{}` or something)
2. another special char or sequence like `\newline` to keep the single line but break it on render

Would that be possible?

Anyway - thanks for your plugin! 😊

**Comment by adifyr** [comment]
Hi @msnr. Thank you for your feedback! As of Version 1.3.0, I've added Markdown & HTML Rendering Support to Chat View Messages. Which means you can now use Markdown and HTML syntax inside the message section of your Chat View. Now you can write Chat View blocks like this:

~~~
```chat
{mw=80}
> Me | Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla. <ol><li>Facilisis at vero eros et accumsan et iusto odio dignissim.</li><li>Qui blandit praesent luptatum zzril delenit augue duis dolore.</li><li>Te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam. Nonummy nibh euismod tincidunt ut laoreet dolore. Magna aliquam erat volutpat. 😄</li></ol> Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat:<br>[https://github.com/adifyr/obsidian-chat-view/issues](https://github.com/adifyr/obsidian-chat-view/issues)<br><br>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. | 16.11.2022 11:39
```
~~~
And it will render as follows:
![image](https://user-images.githubusercontent.com/86793553/202888584-25cc5334-3e4d-4e0d-9404-ad10b0bb2f72.png)
