### ISSUE TITLE
Support for other chat-transcription-syntaxes

### ISSUE THREAD

**Issue by berot3** [adifyr/obsidian-chat-view#18]
Hi,

thank you for this lovely plugin!

How about we add support for more syntaxes (in my case, for Zendesk)?

It would be awesome if you would support the following:

```
(1:38:05 PM) *** Firstname Lastname has joined the chat ***
(1:38:39 PM) Firstname Lastname: This is the chat-text followed after the time and name.
(1:40:26 PM) Other-Firstname Other-Lastname: Sure thanks!
(2:21:29 PM) *** Firstname Lastname has left ***
```

Or are you aware of some other method how I can automatically rewrite the format, so it is compatible with the one from the plugin?

Right now I have to add a `<` at the beginning, add a `|` between name and message and after the message as well as move the time at the end.
For a couple of messages, that's OK, but after a couple of ones... I better ask you what my options are :D

Thanks for your work!

**Comment by adifyr** [comment]
Hi @berot3. May I know more about the format that Zendesk Chat Transcripts use?

1. Is it a standard format? If so, what is the name of the format?
2. If it's a custom format that is unique to Zendesk, could you please post a comprehensive example of a transcript?

Thanks for writing in. Awaiting your response.

**Comment by berot3** [comment]
Hi, thanks for replying!

Regarding 1.: I don't think it is a standard format. But doing a search, you find mostly the formats which I inserted at the end. They are similar but I could not find a standard. It would be interesting to compare chat-transcript-exports of mutliple chat/ticket-systems
- As you can see, most are very simply and dont even use a time-stamp in front. Some use `[ ]` for the time-stamp, other use `( )`
- I left out the first line (followed by an empty line), but I guess it can be ignored in general:

```
Chat started on Tuesday, December 06, 2022 3:19:22 PM

```


Regarding 2.: The example which I have given is already all there is.

---

![image](https://user-images.githubusercontent.com/52616/206125245-aee15565-136a-4be0-83c1-f499d3aa90c4.png)

<img width="647" alt="image" src="https://user-images.githubusercontent.com/52616/206126722-f0ef1823-8e26-488f-a091-977baafa0fd8.png">


![](https://www.comm100.com/wp-content/uploads/2021/04/image/png/Comm100_Live_Chat_Chat_Transcript.png)

**Comment by adifyr** [comment]
### Update

New Chat Mode `chat-transcript` has been added to the plugin draft. This will allow standard transcripts to be appropriately displayed as Chat Views. Following are the features of the `chat-transcript` mode of the Chat View plugin:

1. It properly parses different kinds of chat transcripts; supporting both the `[]` and `()` symbols for timestamps.
2. Allows the user to input both kinds of comments in the transcript. One with the timestamp and the `***` symbol - which is how it works in Zendesk - as well as unformatted lines. Both will be rendered as comments in the final Chat View.
3. All formatting and styling options that are available in other Chat Modes are also available in `chat-transcript`.
4. Delimiters are also available in this mode.

Following is an Example of a Chat View rendered in `chat-transcript` mode. I have used the same snippet that was shared by OP @berot3. Few modifications have been made to showcase all features of new mode:

```chat-transcript
> Other-Firstname Other-Lastname
[Firstname Lastname=blue, Other-Firstname Other-Lastname=pink]
{header=h4, mw=80}

(1:38:05 PM) *** Firstname Lastname has joined the chat. ***
(1:38:39 PM) Firstname Lastname: This is the chat-text followed after the time and name.
...
[1:40:26 PM] Other-Firstname Other-Lastname: Sure thanks! It's nice to have been able to meet someone who could help me with this.
Firstname Lastname has left this chat.
```

The above code-block will render the following Chat View:

![image](https://user-images.githubusercontent.com/86793553/206829253-6c4da4ff-3537-458d-ab45-c501d1f43262.png)

---

@berot3 I believe this covers your use-case completely. Do let me know your feedback. For now, I'll be moving on to creating the release checklist.

**Comment by adifyr** [comment]
### Obsidian Chat View Version 1.4.0 - Release Checklist

Following is the release checklist for Version 1.4.0 of Obsidian Chat View. This release integrates the `chat-transcript` mode with support for Transcripts in various CRMs - as requested in Issue #18.

- [x] Commit Updates to remote `master` branch.
- [x] Update `manifest.json`, `package.json` & `versions.json` versions to 1.4.0.
- [ ] Update README.md to include new guides for `chat-transcript`.
- [ ] Create and publish Release v1.4.0 in `obsidian-chat-view`. (Include `main.js`, `manifest.json` & `styles.css`).

---

- [ ] Close Issue #18 as completed.

**Comment by adifyr** [comment]
Hi @berot3. Version 1.4.0 of Obsidian Chat View has officially been released. Do let me know your feedback. I'll now be closing this issue as completed. Thank you once again for writing in!

**Comment by berot3** [comment]
Thank you so much @adifyr ! This was very fast, I don't even know how to appreciate this. Where is that beer/coffee button? :D

I tested it and it works perfectly.

**Comment by berot3** [comment]
While testing and playing around with it, I was wondering how do I set the chat to the left for both/all chat-members?

Usually I can do this by adding `<` for all. But for transcripts this option is missing, correct? It would be super awesome to have this for transcripts because then it would look more like Zendesk-chat.

**Comment by berot3** [comment]
I am sorry, I was too hasty. I simply added/changed:

```
< Firstname Lastname
< Other-Firstname Other-Lastname
```

And not they are both left aligned. All fine!

**Comment by adifyr** [comment]
Hi @berot3. In the `chat-transcript` mode, all messages are left aligned by default. You don't need to add the arrows. Take a look at the example below:

~~~
```chat-transcript
[Firstname Lastname=blue, Other-Firstname Other-Lastname=pink]
{header=h5, mw=80}

(1:38:05 PM) *** Firstname Lastname has joined the chat. ***
(1:38:39 PM) Firstname Lastname: This is the chat-text followed after the time and name.
[1:40:26 PM] Other-Firstname Other-Lastname: Sure thanks! It's nice to have been able to meet someone who could help me with this.
Firstname Lastname has left this chat.
```
~~~

This will render the Chat View as follows:

![image](https://user-images.githubusercontent.com/86793553/207508914-7c904954-bc2a-4545-9bfe-b65ae335853a.png)

**Comment by adifyr** [comment]
> Thank you so much @adifyr! This was very fast, I don't even know how to appreciate this. Where is that beer/coffee button? :D

Thank you so much @berot3, for your kind words! You can buy me a coffee at the link below. 🙂

<a href="https://www.buymeacoffee.com/adifyr"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee!&emoji=&slug=adifyr&button_colour=5F7FFF&font_colour=ffffff&font_family=Comic&outline_colour=000000&coffee_colour=FFDD00" /></a>
