### ISSUE TITLE
[Feature Request] Auto format clippings from popular chat software like Slack, Skype, Teams etc.

### ISSUE THREAD

**Issue by mayankguptadotcom** [adifyr/obsidian-chat-view#19]
The plugin looks awesome! Great project.
I was wondering if it's possible to auto format (copy/paste)/clippings from popular chat software like Slack, Skype, Teams etc?

**Comment by adifyr** [comment]
Hi @mayankguptadotcom. Chat View already has WebVTT support - which is what a lot of popular chat software like Skype, Meet and Teams use. And [Version 1.4.0](https://github.com/adifyr/obsidian-chat-view/releases/tag/1.4.0) was also very recently released with support for Chat Transcripts - which are used by Customer Support and CRM software like Zendesk.

I highly suggest you read the [documentation for the plugin](https://github.com/adifyr/obsidian-chat-view/blob/master/README.md). If you have a use-case that isn't covered by the plugin, feel free to let me know on this thread.

Awaiting your response.

**Comment by adifyr** [comment]
Hi. Since there has been no response on this thread for the past 5 days. We'll be closing this thread as expired. Please feel free to post another issue if you would like your query resolved. Thank you.
