### ISSUE TITLE
FR: add chat-view-color class  also to the bubble div

### ISSUE THREAD

**Issue by Cammagno** [adifyr/obsidian-chat-view#2]
can the chat-vew-\<color\> class be added also to the bubble div?
In that way, one can use css to personalize the bubble differently for different speaking names :)

**Comment by adifyr** [comment]
I'll have to test it against multiple popular themes and see if the bubble still looks good.
Will look into it.

**Comment by Cammagno** [comment]
> Let me know if this solves your issue so I can close this.

It does, thank you!

**Comment by Cammagno** [comment]
Thanks for the new 1.1.0 release, that included this FR :)

It only leave a small issue; in this way, the customization does not work for the headerless messages (see picture below).

![image](https://user-images.githubusercontent.com/95725064/163674767-e9c59c63-16ec-48c2-b3c5-ba3455dd4744.png)

Maybe is it possible to add the chat-view-color class also to the headerless bubbles following a header bubble?

Like this:

[Me=red, You=green]
< Me | Text            <-this bubble already has .chat-view-red
<  | More Text       <- this bubble should have .chat-view-red
<  | More Text       <- this bubble should have .chat-view-red
> You | Answer    <- this bubble  already has .chat-view-green
> | More Answer   <- this bubble should have .chat-view-green

**Comment by adifyr** [comment]
Could you open a new issue and mark this as a bug?

**Comment by Cammagno** [comment]
> Could you open a new issue and mark this as a bug?

I've created the new issue, but I don't know how to label it as a bug
https://github.com/adifyr/obsidian-chat-view/issues/8

**Comment by adifyr** [comment]
Don't worry. I've taken care of that.
