### ISSUE TITLE
Multiline Support

### ISSUE THREAD

**Issue by max06** [adifyr/obsidian-chat-view#24]
Aloha!

I love the huge amount of input formats! Just one thing: None of them seem to support multiline messages. The only one I found was in your html- and markdown-example, and those newlines are caused by the markdown renderer, not intended by the user. 

I have a lot of files containing email-like messages. Your plugin is used to assemble conversation views. Except that messages are cut off after the first \n. 

Do you see an option to make this work? Maybe by allowing for custom message delimiters, like a double linebreak, or other custom strings?

**Comment by max06** [comment]
I was able to use multiline messages by replacing all `\n` with `</br>`.

Feel free to close this issue if that's good enough for you. 👍🏼

**Comment by adifyr** [comment]
Hi @max06. Yes, using `<br>` is the recommended way to use multiline. 

The reason for that is that incorporating natural multi-line into the Chat View would significantly complicate the parsing of the Chat View - and that would mean you'd have to a lot write more in the code block to render a Chat View (delimiters separating chat bubbles, differentiating between internal new-lines and external) - which isn't what I want for my users. My goal for the plugin is that it should be dead simple to setup - and on top of that allow a lot of flexibility and customizability.

I'll see if I can come up with a multi-line format like that in the future. Thanks for writing in!

**Comment by adifyr** [comment]
Hi @max06. Chat View has officially transitioned to the official Markdown Renderer. And thus more options may now be available. I haven't checked these as of yet. As such, `<br>` is still the recommended way to do new-lines.

**Comment by max06** [comment]
@adifyr ouh, thanks for the heads up! Gonna check it out! 👍🏼

**Comment by elzxr** [comment]
Might it be possible to use a character such as `^` to indicate the line is attached to the conversation above?

```
a < how are you?
b > Great. I have 2 things I want to do today:
^- [ ] thing1
^- [ ] thing2
```

`<br>` breaks checkboxes and bullets from working properly since they are no longer at the start of the line. `<br>` also might work well for pasting saved conversations but is much less pleasant if you're writing out a conversation for yourself. (I've been having fun using this plugin to have introspective conversations)
