### ISSUE TITLE
Words seperated by "|"

### ISSUE THREAD

**Issue by SongshGeo** [adifyr/obsidian-chat-view#25]
## Bug description
I cannot even run the simplest test with all themes, including the default:
![yz9zzZ](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/yz9zzZ.png)

## My attempts

In simpler vault, I confirm `chat-view` works well with these plugins:
```
better-fn
cm-chs-patch
OA-file-hider
obsidian-admonition
obsidian-banners
obsidian-chat-view
obsidian-excalidraw-plugin
obsidian-pandoc-reference-list
obsidian-projects
quickadd
table-editor-obsidian
workspaces-plus
```

## Env exists Problem

- sys: MacOS M2 Pro Max
- Obsidian 1.1.16
- Plugins (Ok.. I admit that I don't have a lot of spare time to test those plugins one by one... any idea?):

```
better-fn
better-word-count
breadcrumbs
calendar
canvas-block-reference
canvas-mindmap
cm-chs-patch
convert-url-to-iframe
cooklang-obsidian
dataview
easy-typing-obsidian
emoji-shortcodes
fantasy-calendar
flashcards-obsidian
float-search
Kanban
make-md
metadata-extractor
nldates-obsidian
note-refactor-obsidian
obisidian-note-linker
obsidian-achievements
obsidian-activity-history
obsidian-admonition
obsidian-advanced-slides
obsidian-annotator
obsidian-another-quick-switcher
obsidian-banners
obsidian-chat-view
obsidian-colorful-tag
obsidian-custom-frames
obsidian-dynamic-highlights
obsidian-electron-window-tweaker
obsidian-emoji-toolbar
obsidian-enhancing-export
obsidian-enhancing-mindmap
obsidian-excalidraw-plugin
obsidian-git
obsidian-global-hotkeys
obsidian-hider
obsidian-hover-editor
obsidian-kanban
obsidian-link-converter
obsidian-linter
obsidian-map-view
obsidian-memos
obsidian-mind-map
obsidian-minimal-settings
obsidian-outliner
obsidian-pandoc
obsidian-pandoc-reference-list
obsidian-plantuml
obsidian-pretty-bibtex
obsidian-projects
obsidian-smart-links
obsidian-stille
obsidian-style-settings
obsidian-timelines
obsidian-to-anki-plugin
obsidian-toggl-integration
obsidian-zotero-desktop-connector
obsidian42-brat
obsidian42-strange-new-worlds
open-with
periodic-notes
QuickAdd
recent-files-obsidian
search-on-internet
SimpRead
smart-connections
surfing
table-editor-obsidian
tag-wrangler
templater-obsidian
uri-commands
workbench-obsidian
```

**Comment by adifyr** [comment]
Hi @SongshGeo. I am not sure I understand your issue. Is it that `Obsidian Chat View` does not work with some plugins? Ideally, that should not happen. It is a self-contained plugin in it's entirety.

I tried the snippet you showed at the top. The very basic sample:
![image](https://user-images.githubusercontent.com/86793553/228129459-d7aadefb-c573-44f7-9102-225addccfe27.png)

But, I found it to be working just fine for my use-case.
![image](https://user-images.githubusercontent.com/86793553/228129524-aaa46a35-83a4-4e83-965b-765377d092ba.png)

Note, that I don't have that many plugins installed. Could you please share the error logs from the Obsidian Console? You can access the console by pressing `Ctrl + Shift + I`. That way, I might be able to get a better idea of what's going on and possibly fix the issue.

**Comment by adifyr** [comment]
Hi @SongshGeo. Since there hasn't been a response for a while, I'll be closing this issue as stale. If you do continue to face any problems relating to this issue, please leave a comment and I'll be happy to reopen it.
