### ISSUE TITLE
🎉 Just praise!

### ISSUE THREAD

**Issue by akaalias** [adifyr/obsidian-chat-view#27]
Hey there @adifyr just wanted to say that I love your plugin AND your syntax for chat formatting.

Great stuff, thank you!

**Comment by adifyr** [comment]
@akaalias, thank you so much! Your comment really means a lot to me. 😄

May I know what you use my plugin for?

**Comment by akaalias** [comment]
Yes, you absolutely may know. 

I usually only care about the final result when I co-edit using [JamGPT](https://www.jamgpt.app/).

But: _Sometimes_ I also want to save the process of how I got there to Obsidian. 

Your plugin helps me do this in two ways: 

1. It provides a simple, future-proof, text-based syntax that JamGPT has adopted.
2. It also renders the conversation in a way that's easier to read later.

My workflow looks a little like this:

<img width="1440" alt="Screenshot 2023-05-07 at 11 19 35" src="https://user-images.githubusercontent.com/111555/236669354-8a87f9d5-5662-411e-8643-4989c384a42d.png">

**Comment by adifyr** [comment]
That is a _VERY_ interesting new use-case! Hadn't thought my plugin could be used that way, but looking at it now, it makes complete sense.

Thank you for sharing! If it's alright, I'd like to feature you on my plugin's main page!
