### ISSUE TITLE
Add ability to customize formatting of chat headers in metadata.

### ISSUE THREAD

**Issue by stoweboyd** [adifyr/obsidian-chat-view#3]
It would be great to include options -- either in the plugin controls, or in the chat metadata -- to change the text rendering. For example:

```chat
[stowe boyd=h3]
> stowe boyd | this is the comment
```
Would lead to a chat box with 'stowe boyd' rendered in whatever h3 styling is set to in the theme. Also, this could make the text in the comment foldable, potentially.

**Comment by stoweboyd** [comment]
PS I note that when a chat is referenced through a transclusion, the header is rendered differently:
![Screen Shot 2022-04-07 at 7 41 20 AM](https://user-images.githubusercontent.com/3037422/162190902-1b724e01-0527-47d2-b538-7c9177e5cd28.png)

**Comment by adifyr** [comment]
> PS I note that when a chat is referenced through a transclusion, the header is rendered differently:
> ![Screen Shot 2022-04-07 at 7 41 20 AM](https://user-images.githubusercontent.com/3037422/162190902-1b724e01-0527-47d2-b538-7c9177e5cd28.png)

Could you open a separate issue for this?

**Comment by adifyr** [comment]
> Would lead to a chat box with 'stowe boyd' rendered in whatever h3 styling is set to in the theme.

Wouldn't it be a bit weird to have styling per member? Ideally, you would have all messages in the chat set to the same header.

> Also, this could make the text in the comment foldable, potentially.

As far as I know, text folding is an obsidian feature. The Chat View is rendered in regular HTML. The title is already an h4. I don't think text folding could work that way.

**Comment by adifyr** [comment]
I've added the ability to customize the style of Chat Headers for the entire block in the new version (1.1.0). You can now add a config to the top of your code block as follows:

`{header=h3}`

This will change the header styles for all Chat Bubbles as it didn't make sense to do it speaker-wise.
