### ISSUE TITLE
Add the ability to set a custom width for the chat bubble.

### ISSUE THREAD

**Issue by zhl111** [adifyr/obsidian-chat-view#4]
Or is it a split column approach?

**Comment by adifyr** [comment]
@zhl111 Hi. Just so I understand your issue. You want to be able to set a **custom width** for the chat bubble?

No, it is not a split column approach.

**Comment by adifyr** [comment]
The Chat Bubbles are set to be dynamically sized based on the size of your text. And the design of Obsidian's plugin development kit means I'd have to set several classes for different sizes of the chat bubbles.

But, I have addressed your underlying issue of the chat bubbles looking too crammed in the mobile UI. The Chat View bubbles will now have a width of 90% on mobile as compared to 75% on desktop.

I might add customization for bubble width sometime in the future. But, for now, I'm closing the issue as resolved.
