### ISSUE TITLE
header does not support Chinese characters, only letters and numbers 

### ISSUE THREAD

**Issue by cumany** [adifyr/obsidian-chat-view#7]
I noticed that the header is filtered with a regular expression, I don't know the reason for this, but it won't display properly with other special symbols or languages
![image](https://user-images.githubusercontent.com/42957010/163660828-08b12ed8-d42b-4c90-bbdd-781c50df9030.png)

**Comment by adifyr** [comment]
Aah, thanks for this. I'll have it fixed in the next patch.

**Comment by adifyr** [comment]
The fix for this issue has been integrated in the latest merge and will be released soon.
