### ISSUE TITLE
Bug: chat-view-color class does not apply to header-less messages

### ISSUE THREAD

**Issue by Cammagno** [adifyr/obsidian-chat-view#8]
see picture below:

![ChatView](https://user-images.githubusercontent.com/95725064/163845039-c0dd36cf-7e03-4019-afce-febc693bbf8b.png)

Maybe is it possible to add the chat-view-color class also to the headerless bubbles following a header bubble?

Like this:

[Me=red, You=green]
< Me | Text <-this bubble already has .chat-view-red
< | More Text <- this bubble should have .chat-view-red
< | More Text <- this bubble should have .chat-view-red
> You | Answer <- this bubble already has .chat-view-green
> | More Answer <- this bubble should have .chat-view-green

**Comment by adifyr** [comment]
I've published a new merge on the `master` branch. Can you check if this fixes your issue?
